name: Deploy Worker Staging
on:
  workflow_dispatch:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: staging
          secrets: |
            SECRET1
          postCommands: |
            wrangler d1 migrations apply stage-admin-console --env staging
        env:
          SECRET1: ${{ secrets.STAGING_SECRET1 }}
